# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='franchise',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='franchise',
            field=models.ManyToManyField(blank=True, null=True, to='core.Franchise'),
        ),
    ]
