# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170609_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
