# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170609_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Franquicias', 'verbose_name_plural': 'Franquicia'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfiles', 'verbose_name_plural': 'Perfil'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='laitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User', verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Franchise', verbose_name='Franquicia'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='tags',
            field=models.ManyToManyField(related_name='franchise_id', to='core.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='franchises',
            field=models.ManyToManyField(related_name='profile_id', to='core.Franchise', verbose_name='Franquisias'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='profile_id', to='core.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='users',
            field=models.ManyToManyField(related_name='profile_id', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Franchise', verbose_name='Franquicia'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.TextField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='restaurant_id', to='core.Profile', verbose_name='PErfiles'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reference',
            field=models.TextField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(related_name='restaurant_id', to='core.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_id', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Última Modificación'),
        ),
    ]
