# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170609_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='created_by',
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(related_name='dish_id', to='core.Tag', verbose_name='Etiquetas'),
        ),
    ]
